version: '3.8'

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:secret@mongo:27017
      MONGO_DB_NAME: reservationsdb

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:secret@mongo:27017
      MONGO_DB_NAME: authdb
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:secret@mongo:27017
      MONGO_DB_NAME: paymentsdb

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:secret@mongo:27017
      MONGO_DB_NAME: notificationsdb

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: pnpm run start:dev gateway
    env_file:
      - ./apps/gateway/.env
    volumes:
      - .:/usr/src/app
    ports:
      - '3004:3004'
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://admin:secret@mongo:27017
      MONGO_DB_NAME: gatewaydb

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
